// =============================================================================
// crm-ingest — Supabase Edge Function (Deno)
//
// Fireflies webhook -> fetch transcript -> Claude synthesis ->
// crm_dev.ingest_meeting(jsonb). Hosted in Supabase; fires on "Summarized".
//
// COST-AWARE INGEST (summary-first, transcript-fallback):
//   1. Pull Fireflies' AI summary (already generated — no extra cost).
//   2. If the summary is empty/void (not ready, or Fireflies didn't make one),
//      pull the full transcript sentences and have Claude synthesize from those.
//   This keeps the common path cheap and only spends on a bigger Claude call
//   when there's genuinely no summary to work from.
//
// Deploy:  supabase functions deploy crm-ingest --project-ref wxkoetczqcpmnuyhsxvo
// Secrets: FIREFLIES_API_KEY, ANTHROPIC_API_KEY, CRM_DB_URL (+ optional
//          FIREFLIES_WEBHOOK_SECRET). See supabase/README.md.
// =============================================================================

import postgres from "https://deno.land/x/postgresjs@v3.4.5/mod.js";

const FIREFLIES_API_KEY = Deno.env.get("FIREFLIES_API_KEY")!;
const ANTHROPIC_API_KEY = Deno.env.get("ANTHROPIC_API_KEY")!;
const DB_URL = Deno.env.get("CRM_DB_URL") ?? Deno.env.get("SUPABASE_DB_URL")!;
const WEBHOOK_SECRET = Deno.env.get("FIREFLIES_WEBHOOK_SECRET"); // optional

// Cap transcript text fed to Claude (~ tokens) to control cost on the fallback.
const TRANSCRIPT_CHAR_CAP = 14000;

const sql = postgres(DB_URL, { prepare: false });

// --- Fireflies queries ------------------------------------------------------
// Primary: summary + attendees (cheap — summary is pre-generated by Fireflies).
const SUMMARY_QUERY = `
  query($id: String!) {
    transcript(id: $id) {
      id title date duration organizer_email
      meeting_attendees { displayName email }
      summary { overview action_items keywords }
    }
  }`;

// Fallback: full sentences (only fetched when the summary is empty).
const SENTENCES_QUERY = `
  query($id: String!) {
    transcript(id: $id) {
      id title date duration organizer_email
      meeting_attendees { displayName email }
      sentences { speaker_name text }
    }
  }`;

async function ff(query: string, id: string) {
  const res = await fetch("https://api.fireflies.ai/graphql", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${FIREFLIES_API_KEY}`,
    },
    body: JSON.stringify({ query, variables: { id } }),
  });
  const json = await res.json();
  if (json.errors) throw new Error("Fireflies: " + JSON.stringify(json.errors));
  return json.data.transcript;
}

// Is the AI summary effectively empty (void)?
function summaryIsEmpty(t: any): boolean {
  const s = t.summary ?? {};
  const overview = (s.overview ?? "").toString().trim();
  const actions = (Array.isArray(s.action_items) ? s.action_items.join("") : (s.action_items ?? "")).toString().trim();
  const keywords = (Array.isArray(s.keywords) ? s.keywords.join("") : (s.keywords ?? "")).toString().trim();
  return !overview && !actions && !keywords;
}

function attendeesBlock(t: any): string {
  return (t.meeting_attendees ?? [])
    .map((a: any) => `- ${a.displayName ?? ""} <${a.email ?? ""}>`).join("\n");
}

// Build the Claude user message from the SUMMARY (preferred path).
function userFromSummary(t: any): string {
  const s = t.summary ?? {};
  const actions = Array.isArray(s.action_items) ? s.action_items.join("\n") : (s.action_items ?? "");
  const keywords = Array.isArray(s.keywords) ? s.keywords.join(", ") : (s.keywords ?? "");
  return `Source: Fireflies AI summary
Meeting: ${t.title ?? "(untitled)"}
Organizer: ${t.organizer_email ?? ""}
Attendees:
${attendeesBlock(t)}

Overview:
${s.overview ?? ""}

Action items:
${actions}

Keywords: ${keywords}`;
}

// Build the Claude user message from raw TRANSCRIPT sentences (fallback path).
function userFromSentences(t: any): string {
  const body = (t.sentences ?? [])
    .map((x: any) => `${x.speaker_name ?? ""}: ${x.text ?? ""}`)
    .join("\n")
    .slice(0, TRANSCRIPT_CHAR_CAP);
  return `Source: raw transcript (no AI summary was available)
Meeting: ${t.title ?? "(untitled)"}
Organizer: ${t.organizer_email ?? ""}
Attendees:
${attendeesBlock(t)}

Transcript (may be truncated):
${body}`;
}

// --- Claude synthesis -------------------------------------------------------
const SYNTH_SYSTEM = `You convert meeting input into a STRICT JSON object for a CRM. Output JSON ONLY — no prose, no markdown fences.

Schema:
{
  "organizations": [{ "ref": "o1", "name": "", "type": "", "notes": "" }],
  "people": [{
    "ref": "p1", "full_name": "", "emails": ["..."],
    "relationship_notes": "",
    "organizations": [{ "org_ref": "o1", "role": "", "is_primary": true }]
  }],
  "interaction": {
    "type": "meeting", "summary": "",
    "decisions": ["..."], "discussion_points": ["..."], "key_points": ["..."],
    "notes": "", "organization_ref": "o1", "participant_refs": ["p1","p2"]
  },
  "tasks": [{
    "title": "", "description": "", "status": "open",
    "due_date": "YYYY-MM-DD or empty", "priority": "high|medium|low or empty",
    "person_ref": "p1", "owner_ref": "me"
  }],
  "recap_email": { "subject": "", "body": "", "to_person_refs": ["p1"] }
}

Rules:
- ref / org_ref / person_ref / owner_ref / participant_refs are YOUR OWN labels wiring records together inside this one JSON. Use "me" as owner_ref for tasks the user owns.
- Use ONLY attendees and emails present in the input. Never invent people, emails, or facts.
- decisions / discussion_points / key_points are arrays of short strings.
- If the input is a raw transcript, write a tight "summary" yourself from it.
- recap_email is a concise post-meeting recap addressed to the other attendees (to_person_refs).
- If something is unknown, use "" or [] — never guess.`;

async function synthesize(userContent: string) {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-6",
      max_tokens: 3000,
      system: SYNTH_SYSTEM,
      messages: [{ role: "user", content: userContent }],
    }),
  });
  const json = await res.json();
  if (json.type === "error") throw new Error("Anthropic: " + JSON.stringify(json.error));
  let text = (json.content?.[0]?.text ?? "{}").trim();
  const first = text.indexOf("{"), last = text.lastIndexOf("}");
  if (first !== -1 && last !== -1) text = text.slice(first, last + 1);
  return JSON.parse(text);
}

// --- optional Fireflies signature verification ------------------------------
async function signatureOk(rawBody: string, header: string | null) {
  if (!WEBHOOK_SECRET) return true;
  if (!header) return false;
  const key = await crypto.subtle.importKey(
    "raw", new TextEncoder().encode(WEBHOOK_SECRET),
    { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  const mac = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(rawBody));
  const hex = [...new Uint8Array(mac)].map((b) => b.toString(16).padStart(2, "0")).join("");
  return header === hex || header === `sha256=${hex}`;
}

Deno.serve(async (req) => {
  if (req.method !== "POST") return new Response("ok", { status: 200 });

  const raw = await req.text();
  if (!(await signatureOk(raw, req.headers.get("x-hub-signature")))) {
    return new Response("bad signature", { status: 401 });
  }

  let body: any = {};
  try { body = JSON.parse(raw); } catch { /* ignore */ }

  // Subscribed to Fireflies "Summarized" only, so any webhook here is wanted.
  const meetingId = body.meetingId;
  if (!meetingId) return new Response("ignored: no meetingId", { status: 200 });

  try {
    // 1. Try the summary first (cheap).
    const t = await ff(SUMMARY_QUERY, meetingId);

    // 2. If the summary is void, fall back to the full transcript.
    let userContent: string;
    let usedFallback = false;
    if (summaryIsEmpty(t)) {
      const t2 = await ff(SENTENCES_QUERY, meetingId);
      userContent = userFromSentences(t2);
      usedFallback = true;
    } else {
      userContent = userFromSummary(t);
    }

    const payload = await synthesize(userContent);

    // Deterministic meta — never trust the model for these.
    payload.interaction = payload.interaction ?? {};
    payload.interaction.source = "fireflies";
    payload.interaction.occurred_at = t.date
      ? new Date(t.date).toISOString() : new Date().toISOString();
    payload.interaction.custom = {
      ...(payload.interaction.custom ?? {}),
      fireflies_id: t.id,
      title: t.title ?? null,
      duration: t.duration ?? null,
      ingest_source: usedFallback ? "transcript" : "summary",
    };

    const [{ interaction_id }] = await sql`
      select crm_dev.ingest_meeting(${ JSON.stringify(payload) }::jsonb) as interaction_id`;

    return new Response(JSON.stringify({ ok: true, interaction_id, via: usedFallback ? "transcript" : "summary" }),
      { status: 200, headers: { "Content-Type": "application/json" } });
  } catch (e) {
    console.error("crm-ingest failed:", e);
    return new Response(JSON.stringify({ ok: false, error: String(e) }),
      { status: 500, headers: { "Content-Type": "application/json" } });
  }
});
